nrwl/nx-cloud-helm

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-pvc.yaml
- charts/nx-cloud/values.yaml
Setting `resourcePolicy` to `"keep"` would allow to retain PVC when Helm release is being deleted. Might be handy when recreating whole Helm release.
> feat: add Helm resource policy annotation for PVC

- PROXY-GUIDE.md
- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-api-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-pvc.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
The Frontend/BFF API and the Nx API need to connect to github/gitlab so they can post PR comments. If the Github instance is self-hosted with a self-signed certificate, those calls fail, because the CA is not among the known trusted ones.
This PR adds support for dealing with self-signed certificates on self-hosted github/gitlab instances, by allowing users to upload their certificate authority and instruct the pods to use it.
> feat: support self signed certs on github gitlab bitbucket instances

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/_images.yml
- charts/nx-cloud/templates/nx-cloud-message-queue-deployment.yaml
This replaces the hardcoded image specified in the messagequeue deployment and allows users to override it with a specific image and tag
> feat(templates): Add ability to override messagequeue image spec

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/_helpers.tpl
Typo on my part, did not notice the '' around the value when I piped to `quote`
> Fix quoting on cloud mode, was using '' and ""

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-workflow-controller-service-account.yaml
The rolebinding should be in the same namespace as the role, not the release namespace.
> fix: sets correct namespace on nx-cloud-workflow-controller-rolebinding

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-workflow-controller-service.yaml
- charts/nx-cloud/values.yaml
Adds support for setting an external name service for the nx-cloud-workflow-controller.
> feat: adds support for using an external name service for the nx-cloud-workflow-controller

- .github/workflows/release_charts.yaml
This will publish charts off of `prerelease/*` branches so we have a way to make new testing releases without merging into main
> chore(infra): Add initial pre-release flow

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-frontend-deployment.yaml
We've merged support for viewing logs within the Nx Cloud app so we need to support setting the required config property in the deployment.
> adds support for setting NX_CLOUD_WORKFLOW_CONTROLLER_ADDRESS

- .github/workflows/chart_lint_and_test.yaml
- .gitignore
- charts/nx-agents/Chart.yaml
- charts/nx-agents/ci/basic-moreenv.yaml
- charts/nx-agents/ci/basic-values.yaml
- charts/nx-agents/templates/deployment.yaml
- charts/nx-agents/values.yaml
- testing-files/secret.yml
When I went to use the chart, I noticed that we did not provide a way to set envFrom. Then while doing those changes
I also noticed we could just use basic yaml instead of doing an array and trying to pull values. This will keep it 
similar to how one would expect it to be in the final manifest.
> chore(charts): ensure env and envFrom can be set, move env to deployment

- charts/nx-agents/Chart.yaml
- charts/nx-agents/templates/_helpers.tpl
- charts/nx-agents/templates/_images.yml
It seems there was some issue where the usage of default without a pipe
makes for a strange behaviour. This was causing the default value in global's
image repository to override everything else
> fix(charts): reorder default in helpers

- charts/nx-agents/Chart.yaml
- charts/nx-agents/ci/basic-moreenv.yaml
- charts/nx-agents/ci/basic-values.yaml
- charts/nx-agents/templates/_images.yml
- charts/nx-agents/values.yaml
I removed the useless global values for image settings as we only use a single image in this chart.
Many of the key values have been documented, hopefully this will make oboarding faster & easier for their
on-prem agents journey.
> chore(charts): get ready for 1.0.0 release

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/ci/basic-values.yaml
- charts/nx-cloud/ci/scm-gh-values.yaml
- charts/nx-cloud/ci/scm-gl-values.yaml
- charts/nx-cloud/ci/sh-like-values.yaml
- charts/nx-cloud/ci/wfcontroller-values-externalservice.yaml
- charts/nx-cloud/ci/wfcontroller-values.yaml
- charts/nx-cloud/templates/_helpers.tpl
- charts/nx-cloud/templates/nx-cloud-aggregator-cron.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-pvc.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-service.yaml
- charts/nx-cloud/templates/nx-cloud-frontend-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-frontend-service.yaml
- charts/nx-cloud/templates/nx-cloud-ingress.yaml
- charts/nx-cloud/templates/nx-cloud-message-queue-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-message-queue-service.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-service.yaml
- charts/nx-cloud/templates/nx-cloud-workflow-controller-service.yaml
- charts/nx-cloud/values.yaml
- use global namespace for all resources
- refactor nxCloudWorkflows to only make a service if it is external. No custom namespace is used
> Update nx-cloud chart

- charts/nx-agents/Chart.yaml
- charts/nx-agents/ci/more-daemonset.yaml
- charts/nx-agents/ci/skipnamespace.yaml
- charts/nx-agents/templates/_images.yml
- charts/nx-agents/templates/daemonset.yaml
- charts/nx-agents/templates/namespace.yaml
- charts/nx-agents/values.yaml
It was pointed out that the namespace could not exist prior to installing
the chart. We have added `global.createNamespace` to control this behaviour.
The image used for the daemonset was not configurable, mainly the registry
and repository portion. We have added `daemonset.image` to control this.
> chore(agents): add ability to change additional values

- charts/nx-agents/Chart.yaml
- charts/nx-agents/ci/basic-values.yaml
- charts/nx-agents/templates/daemonset.yaml
- charts/nx-agents/values.yaml
This is necessary for the Daemonset to run on nodes with taints.
> Allow Configurable Daemonset Tolerations

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/ci/endpointslice-values.yaml
- charts/nx-cloud/templates/nx-cloud-workflow-controller-service.yaml
- charts/nx-cloud/values.yaml
Now that we've verified the changes to the workflows service, we can get rid of pre-release and ship 0.15.0 of the app chart.
> Release 0.15.0

- AGENTS-GUIDE.md
- agents-guide/agents-secrets.yml
- charts/nx-agents/Chart.yaml
- charts/nx-agents/templates/deployment.yaml
- charts/nx-agents/values.yaml
Adds instructions on deploying Valkey to an Nx Agents cluster. This will be needed once the new workflow controller is published.
> add valkey instructions

- AGENTS-GUIDE.md
- charts/nx-agents/Chart.yaml
- charts/nx-agents/templates/deployment.yaml
- charts/nx-agents/values.yaml
Fixes an issue with using a custom valkey url:
> fix valkey url overrides

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
a badly placed `if / else` caused all the startup probes to disappear when a config map was being used
> re-add nx api probes

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-frontend-deployment.yaml
this is something that [we already support on the nx-api](https://github.com/nrwl/nx-cloud-helm/blob/main/charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml#L128-L133) and the aggregator, but was missed from the frontend during a migration
> allow custom ca on frontend

- .github/workflows/chart_lint_and_test.yaml
- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/ci/basic-values.yaml
- charts/nx-cloud/ci/endpointslice-values.yaml
- charts/nx-cloud/ci/scm-gh-values.yaml
- charts/nx-cloud/ci/scm-gl-values.yaml
- charts/nx-cloud/ci/sh-like-values.yaml
- charts/nx-cloud/ci/wfcontroller-values-externalservice.yaml
- charts/nx-cloud/ci/wfcontroller-values.yaml
- charts/nx-cloud/values.yaml
- testing-files/ct.yaml
Without the change `messagequeue` ignores the value set on `global.imageTag`:
With the change default image tag version for `messagequeue` remains `latest`, but it also can be overriden by specifying `global.imageTag` (as for all other images):
> fix: remove default imageTag for messagequeue container

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/_images.yml
I found that when trying to override a single image for the messagequeue
the global values continued to clobber mine as they are the last value
in the default clause. This moves the specific values to the end of the
default params to ensure if you have a more specific value it will
not be overridden by global values.
> chore(app): ensure most specific image spec values have priority

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-message-queue-deployment.yaml
- charts/nx-cloud/values.yaml
With the incoming switch to artemis, we need to be able to override these
values until we do chart 1.0. This should work well enough for us until
that point.
> chore(app): allow user to define/override MQ volumes

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-deployment.yaml
The 'enabled', 'fsGroup', and 'fsGroupChangePolicy' keys were making it
through to the template.spec.containers[0].securityContext section. This
is causing updates to have issues applying.
> fix(app): ensure invalid keys do not make it through

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/ci/basic-values.yaml
- charts/nx-cloud/templates/nx-cloud-aggregator-cron.yaml
- charts/nx-cloud/templates/nx-cloud-file-server-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-frontend-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-message-queue-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
- charts/nx-cloud/values.yaml
Removes the (undocumented) awsS3.serviceAccountName.
> chore(nx-cloud): Allow serviceAccountName to be defined for all nx-cloud deployments

- aws-guide/AWS-GUIDE.md
- aws-guide/helm-values.yml
- add aws policy tag suggestion
- add new aws annotations
> aws guide additions

- charts/nx-agents/Chart.yaml
- charts/nx-agents/templates/executor-binaries-pvc.yaml
we moved the option from `.Values.localExecutorBinaryStorage` to `.Values.localExecutorBinaryStorage.controller` so need to update all references accordingly.
> fix executor binary deployment property references

- charts/nx-agents/Chart.yaml
- charts/nx-agents/templates/deployment.yaml
- charts/nx-agents/values.yaml
this allows loading resource classes from an external configmap. At this time,
the app chart will have to be handled internally as we cannot modify volumes
and mounts for api and aggregator without introducing a breaking change
> chore(workflow-controller): update controller to accept externally defined resource classes

- EXTERNAL-RESOURCE-CLASSES.md
- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/ci/resource-class-config-values.yaml
- charts/nx-cloud/templates/nx-cloud-aggregator-cron.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
- charts/nx-cloud/values.yaml
This introduces the ability to specify external resource classes to the api and aggregator
in a similar fashion to the nx-agents chart. This is primarialy needed as the api serves
as a first line to verify a provided resource class is supported by the system.
> chore(nx-cloud): enable use of external resource classes in app chart

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/ci/volume-helpers-test-values.yaml
- charts/nx-cloud/templates/_helpers.tpl
- charts/nx-cloud/templates/nx-cloud-aggregator-cron.yaml
- charts/nx-cloud/templates/nx-cloud-frontend-deployment.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
- charts/nx-cloud/values.yaml
Internally we have a couple of extra mounts for things and we have to kustomize the yaml
output by helm. Instead let's just make it a bit easier by allowing users (and us) to
provide individual volumes. This is done in a way that still works with resource classes
and self signed certs.
Helpers were added as the conditionals were getting a bit long in the templates and tests
are included to ensure we still get what we expect.
> chore(nx-cloud): ensure custom volumes and mounts can be used

- PROXY-GUIDE.md
- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/_helpers.tpl
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
- charts/nx-cloud/values.yaml
See the docs for an example on how they'd use this: https://github.com/nrwl/nx-cloud-helm/blob/a95fdbde3f6cbc521b0b7c7c5a853800a69ff45d/PROXY-GUIDE.md#pre-built-java-cacerts
> allow defining prebuilt java cert stores

- charts/nx-cloud/Chart.yaml
- charts/nx-cloud/templates/_helpers.tpl
- charts/nx-cloud/templates/nx-cloud-aggregator-cron.yaml
- charts/nx-cloud/templates/nx-cloud-java-security-script-configmap.yaml
- charts/nx-cloud/templates/nx-cloud-nx-api-deployment.yaml
This change improves the Java security directory detection in initContainers by:
1. Creating a centralized ConfigMap with a script that dynamically finds Java security
directories across different distributions and versions
2. Updating both nx-api-deployment and aggregator-cron templates to use this script
3. Adding proper volume mounts and references in the helper templates
The script prioritizes Amazon Corretto installations but includes fallbacks for other
Java distributions. It checks multiple common security directory locations to ensure
compatibility with various Java versions.
This fixes issues when updating Java images where hardcoded paths may no longer exist.
> fix(nx-cloud): make Java security path detection robust
